- name: Add docker apt repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    update_cache: yes

- name: update apt
  become: yes
  apt: state=present update_cache=yes force=yes


- name: Install Docker apt package
  become: yes
  apt: name=docker-ce state=present force=yes

- name: Ensure Docker service is installed and restarted
  become: yes
  service:
    name: docker
    state: restarted
    enabled: yes
- name: Install Docker Compose (if configured).
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755